# Generated by Django 4.2.25 on 2025-10-21 15:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('callsign', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('Offline', 'Offline'), ('Available', 'Available'), ('Busy', 'Busy')], db_index=True, default='Offline', max_length=16)),
                ('lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('lng', models.FloatField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_phone', models.CharField(db_index=True, max_length=32)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('from_lat', models.FloatField(blank=True, null=True)),
                ('from_lng', models.FloatField(blank=True, null=True)),
                ('to_lat', models.FloatField(blank=True, null=True)),
                ('to_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('DriverAssigned', 'Driver assigned'), ('OnTrip', 'On trip'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Created', max_length=32)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dispatch_core.driver')),
            ],
        ),
    ]
