# Generated by Django 4.2.25 on 2025-10-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideorder',
            name='from_lat',
        ),
        migrations.RemoveField(
            model_name='rideorder',
            name='from_lng',
        ),
        migrations.RemoveField(
            model_name='rideorder',
            name='to_lat',
        ),
        migrations.RemoveField(
            model_name='rideorder',
            name='to_lng',
        ),
        migrations.AlterField(
            model_name='driver',
            name='callsign',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('Available', 'Свободен'), ('Busy', 'Занят'), ('Offline', 'Оффлайн')], default='Offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch_core.driver'),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='customer_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rideorder',
            name='status',
            field=models.CharField(choices=[('New', 'Новый'), ('DriverAssigned', 'Назначен водитель'), ('Completed', 'Выполнен'), ('Cancelled', 'Отменён')], default='New', max_length=20),
        ),
    ]
