# Generated by Django 4.2.25 on 2025-10-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_core', '0002_remove_rideorder_from_lat_remove_rideorder_from_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideorder',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='from_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='from_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='to_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rideorder',
            name='to_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
